name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: elementary/docker:unstable-next
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y libaccountsservice-dev libibus-1.0-dev libgnome-desktop-3-dev libgranite-7-dev libswitchboard-3-dev meson policykit-1 valac
    - name: Build
      env:
        DESTDIR: out
      run: |
        meson build
        ninja -C build install

  lint:

    runs-on: ubuntu-latest
    
    container:
      image: valalang/lint
      
    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: io.elementary.vala-lint -d .
